on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install
      run: yarn install #--frozen-lockfile
    #- name: lint
    #  run: yarn lint
    - name: test
      run: yarn test
  publish_alpha:
    name: publish alpha release
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: fetch tags
      run: git fetch origin +refs/tags/*:refs/tags/*
    - name: configure git
      run: |
        git config user.email "typescriptbot@microsoft.com"
        git config user.name "TypeScript Bot"
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org
    - name: install
      run: yarn install --frozen-lockfile
    - name: build
      run: yarn build
    - name: publish alpha
      run: yarn lerna publish prerelease -y --pre-dist-tag next --preid next
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
